### ISSUE TITLE
Configure the development environment and frontend app 

### ISSUE THREAD

**Issue by JSnow11** [Full-Tortuga/decide-full-tortuga-admin#1]
# description
Configuración inicial del entorno de desarrollo y la aplicación react a implementar.

# to-do
- [x] create new administration module
- [x] configure react app

# accept
- [x] app accessible on /administration on local env
- [x] app dev env accessible running `npm start` on localhost:3000

**Comment by JSnow11** [comment]
# implemented
## test
- setup your local env
- check /administration url
- check configurations
- build the app in /frontend : `npm install` y `npm run build`
