### ISSUE TITLE
Bulk delete

### ISSUE THREAD

**Issue by JSnow11** [Full-Tortuga/decide-full-tortuga-admin#14]
# description

# to-do
- [x] Implementar bulk delete
- [x] Refactorizar todo el código afectado

# accept
- [x] Los endpoint de delete all ahora permiten borrar pasando una lista de ids
