### ISSUE TITLE
Lista de usuarios

### ISSUE THREAD

**Issue by JSnow11** [Full-Tortuga/decide-full-tortuga-admin#17]
# description

# to-do
- [x] listar usuarios
- [x] action bar de usuarios

# accept
- [x] usuarios pueden ser listados
- [x] usuarios pueden ser eliminados
- [x] usuarios pueden cambiar de estado
