### ISSUE TITLE
Backend pagination and sort for tables

### ISSUE THREAD

**Issue by JSnow11** [Full-Tortuga/decide-full-tortuga-admin#27]
# description

# to-do
- [ ] establecer paginación
- [ ] establecer ordenación de mas reciente a mas antiguo en las respuestas del backend
- [ ] documentar el uso de la paginación y crear tarea para el frontend

# accept
- [ ] las peticiones de listado de usuarios y votaciones tienen paginación y ordenación
