### ISSUE TITLE
Acciones de estado de usuario

### ISSUE THREAD

**Issue by JSnow11** [Full-Tortuga/decide-full-tortuga-admin#31]
# description
![image](https://user-images.githubusercontent.com/47798577/146649250-e47d0da3-a0b2-40ec-8aca-1aaeacf733f2.png)

# to-do
- [x] crear una API para gestionar el estado del usuario
- [x] las operaciones seran bulk
    - [x] update activacion (solo pasando lista de ids de usuario y true or false)
    - [x] update staff (solo pasando lista de ids de usuario y true or false)
    - [x] update admin (solo pasando lista de ids de usuario y true or false)

# accept
- [x] se puede actualizar el estado con operaciones bulk
