### ISSUE TITLE
Formulario crear/editar usuario

### ISSUE THREAD

**Issue by JSnow11** [Full-Tortuga/decide-full-tortuga-admin#38]
# description
necesitamos un formulario de creación/edicion de usuarios

el formulario ya esta planteado como un modal, en la carpeta `templates/users`
# to-do
- [x] completar el formulario con los inputs requeridos
- [x] asegurar que el usuario inicial se carga como valores por defecto para la edición
- [x] hacer uso de las llamadas a la api para crear/editar

# accept
- [x] se puede crear/editar usuarios
