### ISSUE TITLE
Configurar Docker

### ISSUE THREAD

**Issue by JSnow11** [Full-Tortuga/decide-full-tortuga-admin#40]
# description
Necesitamos que el proyecto sea desplegable como contendor.
Para ello se configurarán los diferentes procesos de despliegue manual en los archivos de docker.

Se debe configurar y automaticar el despliegue django y el la construcción (build) de la app react. 

# to-do
- [x] configurar docker
    - [x] dockerfile
    - [x] docker-compose
    - [x] docker-settings.py 
- [x] documentar el proceso de configuración

# accept
- [ ] el proyecto es facilmente desplegable como contenedor
