### ISSUE TITLE
Automatizar despliegue en heroku

### ISSUE THREAD

**Issue by JSnow11** [Full-Tortuga/decide-full-tortuga-admin#41]
# description
El despliegue en heroku debe automatizarse, para ello se hará uso de github actions.

Cuando se realice un nuevo commit a develop o a main se debe realizar un push a heroku. Se mantendrán dos aplicaciones en cuentas diferentes. Una para test (develop) y otra para producción (main). 

**Nota**: se recomienda que las configuraciones concretas de heroku sean gestionadas en el `procfile` y se cree un `local-settings.test.py` y un `local-settings.prod.py` para poder configurar django de forma concreta en cada entorno.
En el frontend se debe re-configurar la url de producción de la API en el archivo `axios.ts`

# to-do
- [ ] crear las 2 apliaciones de heroku
- [ ] revisar el proceso de despliegue manual en heroku
- [ ] automatizar y unificar.

# accept
- [ ] el proceso de despliegue esta automatizado
