### ISSUE TITLE
backend tests

### ISSUE THREAD

**Issue by JSnow11** [Full-Tortuga/decide-full-tortuga-admin#43]
# description
Se deben testear los nuevos controladores ofrecidos para garantizar su correcto funcionamiento y que cumplen con su función.

# to-do
- [ ] añadir tests en el modulo administration
- [ ] asegurar un buen nivel de coverage
- [x] #74
- [x] #75
- [x] #76
- [x] #77
- [x] #78
- [x] #79
- [x] #80
- [x] #81

# accept
- [ ] los tests pasan correctamente e indican un buen nivel de coverage para el módulo administration
