### ISSUE TITLE
Plantilla de commits

### ISSUE THREAD

**Issue by JSnow11** [Full-Tortuga/decide-full-tortuga-admin#44]
# description
necesitamos que el mensaje de commit tenga una plantilla determinada

la plantilla debe gestionar **el issue relacionado** y el **tipo de commit**

# to-do
- [ ] crear la plantilla
- [ ] asegurar que salta cuando se trata de realizar un commit

# accept
- [ ] se tiene una plantilla de commit disponible
