### ISSUE TITLE
Add react modules and base structures

### ISSUE THREAD

**Issue by JSnow11** [Full-Tortuga/decide-full-tortuga-admin#5]
# description
necesitamos establecer las lineas base de desarrollo de la aplicación de frontend en react, para ello configuraremos

- import structure
- routes
- api calls
- styles with tailwind 
- utils

# to-do
- [x] configure import urls and structure
- [x] create Route Configurations
- [x] create basic api calls structure
- [x] error handling
- [x] install tailwind module
- [x] create basic utils structure

# accept
- [x] react boilerplate ready
- [x] react app structure correctly established
