### ISSUE TITLE
CRUD Operations Auth and Key

### ISSUE THREAD

**Issue by josaloroc** [Full-Tortuga/decide-full-tortuga-admin#9]
# description
CRUD Operations for Auth and Key from base module
# to-do
- [x] Implement a restful api for Auth CRUD operations
- [x] Implement a restful api for Key CRUD operations

# accept
- [x] Create, Read, Update and delete an Auth
- [x]  Create, Read, Update and delete a Key
